language: cpp
dist: xenial
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
# whitelist
branches:
  only:
    - master

scripts:
  - cmake .
  - make
  - ./test --success